-- Root Cause Analysis — human-confirmed root cause per production batch.
-- Run ONCE in the Production-FMS Supabase project (ref bliuwvkdtvxmteyzuzds) → SQL editor.
-- The RCA app works read-only without this table; recording a root cause needs it.
-- This is the ONLY table the RCA app writes to. Never alter Production-FMS tables from this app.

create table if not exists public.rca_reviews (
  id                    bigint generated by default as identity primary key,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  -- link to the batch (actual_production.id) + denormalised context for reporting
  actual_production_id  bigint not null,
  production_id         bigint,
  job_card_no           text,
  firm_name             text,
  order_no              text,
  product_name          text,
  composition_no        text,

  -- what the RCA engine saw when the review was written
  deviation_severity    text check (deviation_severity in ('ok', 'minor', 'major')),
  mix_shift             numeric,

  -- the human answer
  root_cause_category   text not null check (root_cause_category in (
                          'Planned composition change',
                          'Raw material shortage / substitution',
                          'Raw material quality (lot variation)',
                          'Weighing / measurement error',
                          'Operator / process error',
                          'Data entry error (unit / qty)',
                          'Lab instruction',
                          'Other')),
  root_cause_detail     text,
  corrective_action     text,
  preventive_action     text,
  status                text not null default 'Open' check (status in ('Open', 'Closed')),
  reviewed_by           text
);

create index if not exists rca_reviews_batch_idx on public.rca_reviews (actual_production_id);
create index if not exists rca_reviews_order_idx on public.rca_reviews (order_no, product_name);

create or replace function public.rca_reviews_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- No DROP statements anywhere in this file (Supabase flags them as destructive). Everything below only
-- creates NEW objects that belong to rca_reviews. If you run the file a second time, the policy lines
-- will say "already exists" — that is harmless, nothing is changed.
create or replace trigger trg_rca_reviews_touch before update on public.rca_reviews
  for each row execute function public.rca_reviews_touch();

-- The ecosystem uses the anon key from the browser (no Supabase Auth). Allow read + insert + update,
-- but not delete, so history of root causes is never lost from the app.
alter table public.rca_reviews enable row level security;

create policy rca_reviews_select on public.rca_reviews for select to anon, authenticated using (true);
create policy rca_reviews_insert on public.rca_reviews for insert to anon, authenticated with check (true);
create policy rca_reviews_update on public.rca_reviews for update to anon, authenticated using (true) with check (true);

grant select, insert, update on public.rca_reviews to anon, authenticated;
