-- RCA Assistant (chatbot) history — one row per question + answer.
-- Run ONCE in the Production-FMS Supabase project (ref bliuwvkdtvxmteyzuzds) → SQL editor.
-- Only creates NEW objects for rca_chat_logs; no DROP statements; nothing else in Production-FMS is touched.
-- The chatbot keeps working without this table — it just doesn't save history until this is run.

create table if not exists public.rca_chat_logs (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),

  user_id          text,          -- login."ID"
  username         text,          -- login."User name"
  firm             text,          -- login."Firm" (empty for admins = all firms)
  role             text,          -- admin / user

  conversation_id  text,          -- groups the questions of one chat (resets on "New")
  question         text not null,
  answer           text,
  tools_used       text[],        -- e.g. {get_batch,business_summary}
  status           text not null default 'ok' check (status in ('ok', 'error', 'stopped')),
  error            text,
  duration_ms      integer,
  page             text           -- app page the question was asked from
);

create index if not exists rca_chat_logs_created_idx on public.rca_chat_logs (created_at desc);
create index if not exists rca_chat_logs_user_idx on public.rca_chat_logs (username, created_at desc);

-- Browser uses the anon key (no Supabase Auth), same as rca_reviews: allow insert + read, no update/delete.
alter table public.rca_chat_logs enable row level security;

create policy rca_chat_logs_select on public.rca_chat_logs for select to anon, authenticated using (true);
create policy rca_chat_logs_insert on public.rca_chat_logs for insert to anon, authenticated with check (true);

grant select, insert on public.rca_chat_logs to anon, authenticated;
